### ISSUE TITLE
The project can't run.. Some files are missing.

### ISSUE THREAD

**Issue by kazimdsaidul** [developerSajib88/BurgerKing-Restaurant-App-IOS-Android#1]
The project can't run. Some files are missing. I think you missing adding to the repository .

1. SplashScreen, 
2. profile page, 
3. PizzaList, 
4. SandwichList
5. StoreList

**Comment by HelloSajib** [comment]
> The project can't run. Some files are missing. I think you missing adding to the repository .
> 
> 1. SplashScreen,
> 2. profile page,
> 3. PizzaList,
> 4. SandwichList
> 5. StoreList

Thank you for give this issues and very soon i will add full this project. Thank you Saidul bhay.

**Comment by HelloSajib** [comment]
> The project can't run. Some files are missing. I think you missing adding to the repository .
> 
> 1. SplashScreen,
> 2. profile page,
> 3. PizzaList,
> 4. SandwichList
> 5. StoreList

I uploaded this full project in rar files. Thank you
